/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/demos/': RouteRecordInfo<'/demos/', '/demos', Record<never, never>, Record<never, never>>,
    '/demos/2024-02-02': RouteRecordInfo<'/demos/2024-02-02', '/demos/2024-02-02', Record<never, never>, Record<never, never>>,
    '/diary': RouteRecordInfo<'/diary', '/diary', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/atan2': RouteRecordInfo<'/posts/atan2', '/posts/atan2', Record<never, never>, Record<never, never>>,
    '/posts/blog_evolution_journey': RouteRecordInfo<'/posts/blog_evolution_journey', '/posts/blog_evolution_journey', Record<never, never>, Record<never, never>>,
    '/posts/note/jetbrains_activation': RouteRecordInfo<'/posts/note/jetbrains_activation', '/posts/note/jetbrains_activation', Record<never, never>, Record<never, never>>,
    '/posts/note/wsl': RouteRecordInfo<'/posts/note/wsl', '/posts/note/wsl', Record<never, never>, Record<never, never>>,
    '/posts/note/锻炼脑力': RouteRecordInfo<'/posts/note/锻炼脑力', '/posts/note/锻炼脑力', Record<never, never>, Record<never, never>>,
    '/posts/摩擦和重力的物体运动与角度计算': RouteRecordInfo<'/posts/摩擦和重力的物体运动与角度计算', '/posts/摩擦和重力的物体运动与角度计算', Record<never, never>, Record<never, never>>,
    '/posts/日语': RouteRecordInfo<'/posts/日语', '/posts/日语', Record<never, never>, Record<never, never>>,
    '/posts/黑魂复刻第一季-傅老师': RouteRecordInfo<'/posts/黑魂复刻第一季-傅老师', '/posts/黑魂复刻第一季-傅老师', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/talks': RouteRecordInfo<'/talks', '/talks', Record<never, never>, Record<never, never>>,
  }
}
